version: '3.8'

services:
  app:
    build: .
    container_name: hospital_registration_app
    env_file: .env
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - hospital_network

  db:
    image: postgres:13
    container_name: hospital_registration_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hospital_network

networks:
  hospital_network:
    driver: bridge

volumes:
  postgres_data:
