apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-registration-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-registration-db
  template:
    metadata:
      labels:
        app: hospital-registration-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "hospitaldb"
            - name: POSTGRES_USER
              value: "youruser"
            - name: POSTGRES_PASSWORD
              value: "yourpassword"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
