apiVersion: v1
kind: Service
metadata:
  name: hospital-registration-app
spec:
  selector:
    app: hospital-registration-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
